Metrics/LineLength:
  Max: 120

Style/Documentation:
  Enabled: false

Style/NonNilCheck:
  IncludeSemanticChanges: true

Metrics/BlockLength:
  Exclude:
  - config/initializers/simple_form_bootstrap.rb
  - 'Rakefile'
  - '**/*.rake'
  - 'spec/**/*.rb'

Style/FileName:
  Exclude:
  - 'Gemfile'

Style/FrozenStringLiteralComment:
  Enabled: false

AllCops:
  TargetRubyVersion: 2.4
  Include:
    - 'config.ru'
  Exclude:
    - 'bin/**/*'
